### ISSUE TITLE
Missing overflow hidden on code block

### ISSUE THREAD

**Issue by slafleche** [vanilla/docs#249]
We want to keep " white-space: pre;" on code, but allow horizontal scrolling. [See this page as an example of a broken page](https://docs.vanillaforums.com/developer/framework/modules/).

**Comment by charrondev** [comment]
Related https://github.com/vanilla/docs/issues/209 related #195 

The issue seems to stem from old converted pages that are actually written in HTML and not markdown. As a result the proper class/html structure is not created, and are full code block styles don't apply. We should be converting these pages to markdown as we come across them
