### ISSUE TITLE
Vanilla CLI setup install missing source directory step

### ISSUE THREAD

**Issue by linc** [vanilla/docs#359]
Following [these instructions](https://docs.vanillaforums.com/developer/vanilla-cli/installation/#installation-with-composer) under "Installation with Composer", I then return to the [Boilerplate Getting Started](https://docs.vanillaforums.com/developer/theme-boilerplate/#getting-started) and run 'vanilla build'.

This error is generated:

> Vanilla source directory is missing.
> Please provide a path to your vanilla installation with the "--vanillasrc" parameter or by setting the VANILLACLI_VANILLA_SRC_DIR environmental variable.

Searching the docs yields 1 mention of this, in a different doc not about setup: https://docs.vanillaforums.com/developer/vanilla-cli/#addon-utilities

These docs don't make it entirely clear how the path is being used so it's difficult to adapt it to my setup.

**Comment by charrondev** [comment]
Point it to your source directory of vanilla that you're using. If your vanilla installation is at `~/workspace/vanilla` then that is the path you use. This whole step is required because when the CLI was created someone on R&D insisted I not locate place the build tool in the main vanilla repo (which we've now gone back on).

Devs tend to have multiple vanilla-cli versions, and the tool needs to know which one you want to work with.

**Comment by linc** [comment]
I figured it out just fine and moved on, this is just me pointing out the bug in the docs because I didn't feel like I was the right person to explain it / update the docs.

Someone with less strong knowledge of CLI flags and our product's quirks could get stuck here easily.
