### ISSUE TITLE
Is there a "VanillaForums.org" newsletter?

### ISSUE THREAD

**Issue by R-J** [vanilla/docs#52]
In the [docs](https://github.com/vanilla/docs/blob/master/content/developer/community/index.md) is mentioned that you can subscribe to a newsletter when you visit [your profile](open.vanillaforums.com/profile/edit)

I haven't found anything like that...

**Comment by linc** [comment]
It was axed by marketing a year or two ago. Nothing to stop us from starting a new one.

**Comment by linc** [comment]
@adrianspeyer ?

**Comment by adrianspeyer** [comment]
The newsletter option in the profile was something different, and long ago removed (circa 2013). Since then,  when you download Vanilla, you have the option to be notified of any issues with the open source (such as a new version) or anything applicable. So while it is not an "open source" newsletter per say, we are still communicating with the open source.

**Comment by adrianspeyer** [comment]
To that end, I have updated the download form to be more accurate to note that downloaders opt to get updates from Vanilla.
